---

# TODO:
# - check locks
# - add retries

- name: 'pkg_add'
  openbsd_pkg:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    clean: True
  loop: "{{ pkg_list }}"
