---

# TODO:
# - check locks
# - add retries

- name: install/remove packages
  openbsd_pkg:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    purge: True
  loop: "{{ pkg_list }}"
