---

- hosts: all
  name: 'Verify'
  become: True
  gather_facts: True

  tasks:
    - name: 'Retrieve the list of packages'
      package_facts:
        manager: 'auto'

    - name: 'Check the packages are installed'
      assert:
        that:
          - "'lynx' in ansible_facts['packages']"
          - "'alpine' in ansible_facts['packages']"
